name: Download File and Push to Main
on: 
  workflow_dispatch:
jobs:
  download_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download File
        run: wget 'https://software.download.prss.microsoft.com/dbazure/Win11_24H2_Chinese_Simplified_x64.iso?t=4f88164b-66d0-4fb4-bd94-3b690b81446c&P1=1732024479&P2=601&P3=2&P4=lHQFa%2fTb%2fpqJz9x7Uh%2f%2fZG3iy2MwW35X3%2fHHamPMyJVFHDpKcvuCt1jKKD8OC0fXeS6GNeo2h8FAamTjTcUTdkPVveP3hEHXc4ZomZ2NyZ2c9v8o8bSdnsY3AoyMmOuf4gZnjgsAOoVpZJIJ8tiIk%2b8%2f6x0hfDSN%2fGZqFgOcyRrQDM4rYBP82m7TVsfhjglkrSXjvnH2A1AgVOaNuuQ1DVeKkbCI4WjlUZit%2fvpwoswY3miVXjz5AHXjrQOLiLxakTz%2fka8gZJAOYXIsqreBsLy5Se3SixGHTLn%2fe2igZJYG4yPuOiKnUSdO3fon6ZpOxuGhuT5O9U2m0uJ9WQaKHw%3d%3d'  # 将这里的链接替换为你实际要下载的文件的HTTP链接
      - name: Add and Commit File
        run: |
          git add.
          git commit -m "Add downloaded file"
      - name: Push to Main Branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.APITOKEN }}
          branch: main
