name: Download File and Push to Main
on: 
  workflow_dispatch:
jobs:
  download_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download File
        run: wget 'http://down.bfxitong.com/2024/2407/win7-64c-24.7.gho'  # 将这里的链接替换为你实际要下载的文件的HTTP链接
      - name: Add and Commit File
        run: |
          git config --local user.email "xumouren225588@163.com"
          git config --local user.name "xumouren225588"
          git add .
          git commit -m "添加Windows7镜像"
          git push

